#!/bin/bash

if [ "$TEST_SUITE" == "ruby" ]; then
  bundle exec rspec spec
elif [ "$TEST_SUITE" == "phantomjs" ]; then
  bundle exec rackup -s puma -p 5000 -D
  sleep 3
  phantomjs run_qunit.js http://localhost:5000/spec.html
elif [ "$TRAVIS_SECURE_ENV_VARS" == "true" -a "$TEST_SUITE" == "saucelabs" ]; then
  bundle exec rackup -s puma -p 5000 -D
  sleep 3
  curl -L https://gist.githubusercontent.com/henrikhodne/9322897/raw/sauce-connect.sh | bash
  gem install selenium-webdriver
  ruby script/saucelabs.rb
else
  echo "Not running any tests"
fi
